FROM tomcat:latest
MAINTAINER vijayabalan has created this container based tomcat
MAINTAINER artifacts will be copied from jenkins build server
MAINTAINER Then war file will be deployed into tomcat which is running on container
COPY ./gameoflife.war /usr/local/tomcat/webapps/
